set terminal pngcairo size 1024,768 enhanced font 'Verdana,10'
set output 'coin_convergence.png'

set title "Convergence of Probability: Fair vs Biased Coin"
set xlabel "Number of Tosses"
set ylabel "Cumulative Probability of Heads"
set yrange [0:1]
set grid

# Draw dashed horizontal line for the Fair Coin theoretical probability (0.5)
set arrow 1 from graph 0,first 0.5 to graph 1,first 0.5 nohead lc rgb "blue" dt 2 lw 2
set label 1 "Fair (0.50)" at graph 0.8, first 0.47 textcolor rgb "blue"

# Plot the data generated by your C program
plot 'coin.dat' using 1:2 with lines lc rgb "blue" title 'Fair Coin', \
     'coin.dat' using 1:3 with lines lc rgb "red" title 'Biased Coin'